using FluentValidation;

namespace Application.Pricing.Queries.GetPendingPriceEntryDisputes;

public sealed class GetPendingPriceEntryDisputesQueryValidator : AbstractValidator<GetPendingPriceEntryDisputesQuery>;
