using FluentValidation;

namespace Application.Products.Queries.GetPendingProductSubmissions;

public sealed class GetPendingProductSubmissionsQueryValidator : AbstractValidator<GetPendingProductSubmissionsQuery>;
